import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import styles from '../styles/Home.module.css'
import About from './About';
import Contact from './Contact';
import Experience from './Experience';
import Main from './Main';
import Navbar from './Navbar'
import Works from './Works';



export default function Home() {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.bundle.min.js')
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Abhishek Gattineni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Experience />
      <Works />
      <Contact />

    </div>
  )
}
